name: CI

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 30

    strategy:
      fail-fast: false
      matrix:
        node-version: [ '15', '12', '14' ]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Configure npm time machine registry
      run: |
        npm config set registry https://time-machines-npm.sealsecurity.io/
        npm config set //time-machines-npm.sealsecurity.io/:_authToken=2021-04-14T21:07:09.057000Z

    - run: npm install

    - run: npm test

  package:

    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 15
      uses: actions/setup-node@v4
      with:
        node-version: '15'

    - name: Configure npm time machine registry
      run: |
        npm config set registry https://time-machines-npm.sealsecurity.io/
        npm config set //time-machines-npm.sealsecurity.io/:_authToken=2021-04-14T21:07:09.057000Z

    - run: npm install

    - run: npm pack --ignore-scripts

    - name: Upload npm tarball
      uses: actions/upload-artifact@v4
      with:
        name: npm-tarball
        path: '*.tgz'
        if-no-files-found: error
